### ISSUE TITLE
React warnings and watch issues

### ISSUE THREAD

**Issue by adamwoodnz** [svenanders/ReactJSBlueprints_Chapter2#1]
I've run into issues almost immediately trying to work with this chapter.

Steps to reproduce issues:
1. Clone repo
2. npm i
3. npm start
4. Click item to navigate to http://localhost:3000/item/FAN

Get a React warning: 'warning.js:45Warning: Failed propType: Invalid prop `bsSize` of value `medium` supplied to `Button`, expected one of ["lg","large","sm","small","xs","xsmall"]. Check the render method of `ProductInfo`.'

Not a big deal, I've worked with React for a while now so I understand the warning and I try to change the prop to 'sm'.

The watch fails:

[BS] File changed: source/pages/item.jsx
/item/FAN
Error: ENOENT: no such file or directory, stat '/Users/adam/Sites/github/svenanders/ReactJSBlueprints_Chapter2/public/item/app.css'
    at Error (native)
/item/bundle.js

The bundle is not rebuilt, and in the browser bundle.js has an html response:
bundle.js:1 Uncaught SyntaxError: Unexpected token <

Not a great first time experience. Is the watch supposed to recomplile? I don't see the point of having a browsersync session if you can't hotload...

**Comment by robbestad** [comment]
Hi, thanks for reporting. This is really weird, because it did work out of the box for me (on my last checkout). I'll reproduce now and update ASAP.

And yep, it's supposed to recompile and refresh the browser.

**Comment by robbestad** [comment]
Hi again,

The issue was the server routing. When you're on a sub route and change the code, browser-sync will reload the page. The router was set up so that it would try to locate the JavaScript and the CSS on the subroute path (which doesn't exist). That's when you end up with  `Unexpected token <` because the router simply serves `index.html` instead of the desired resource.

I think react-bootstrap once supported the _medium_ property, but i may be mistaken. In any case, it's not supported, and so I replaced it with _large_. 

In light of this, I think  I need to change the server.js code for all the chapters using Browserify (1-5).

**Comment by adamwoodnz** [comment]
Thanks, I'll have another go asap.

**Comment by adamwoodnz** [comment]
Looks good, thanks
